os: linux
language: dart
dist: xenial
sudo: false

addons:
  apt:
    packages:
      - lib32stdc++6

install:
  - cd .. && wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.7.8+hotfix.4-stable.tar.xz
  - tar xf flutter_linux* && export PATH="$PATH:`pwd`/flutter/bin" && cd $TRAVIS_BUILD_DIR
  - flutter doctor

script:
  - ./check_project.sh

cache:
  directories:
    - $HOME/.pub-cache