name: flutter_sample
description: "A new Flutter project."
version: 1.0.0+1

dependencies:
  eva_icons_flutter: ^1.0.4
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  rxdart: ^0.22.1
  transparent_image: ^1.0.0
  flutter: 
    sdk: flutter

dev_dependencies:
  coveralls: ^5.3.0
  mockito: ^4.1.0
  flutter_test: 
    sdk: flutter

environment: 
  sdk: ">=2.1.0 <3.0.0"

flutter: 
  assets: 
    - assets/
  uses-material-design: true